version: 0.1.1
default:
  # PostgresSQL
  POSTGRES_CONNECT_TIMEOUT: 10
  POSTGRES_DBNAME: postgres
  POSTGRES_SCHEMA: raw
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: dsde
  POSTGRES_HOST: 3.107.190.187
  POSTGRES_PORT: 5432

